# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main'  ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: download-tools
      run: make download-tools

    - name: build
      run: make GOTIFY_VERSION="v2.5.0" build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webhook-linux-amd64.so
        path: |
          build/webhook-linux-amd64.so
          build/webhook-linux-arm-7.so
          build/webhook-linux-arm64.so
          
